[package]
name = "mike"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[build-dependencies]
classico-wd40 = { path = "../../classico/classico/wd40" }
